### ISSUE TITLE
Abuna Marqos 1881

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Authority-Files#11]
I don't seem to be able to find a person file for Abuna Marqos, appointed with Matewos, Luqas, and Petros at the request of Yojannes IV. 

https://betamasaheft.eu/persons/PRS6876Matewos/main, on Matewos, refers to Luqas and Petros but refers back to itself rather than mentioning the shortlived Marqos.

**Comment by thea-m** [comment]
@DariaElagina @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
Indeed, it should have been there, since this bishop is mentioned in the EAE (II:343b; III:867a,1059b; IV:139a) and once the register was authomatically converted into records, but he is not there. At least I could not locate him. There is a number of other people bearing the same name, doing upproximately the same, and his appearance n the mss we recoded may be minimal. I think it will be ok if you just create a record for him, disambiguating him as clear as possible.  
--


,

**Comment by Ralph-Lee-UK** [comment]
I'll do that, and use the information from Matewos to make it clear who he is.
